###########################################################
#     bbCheck.yml
#
#     Copyright IBM Corporation 2020 All Rights Reserved
#
#     This program is licensed under the terms of the Eclipse Public License
#     v1.0 as published by the Eclipse Foundation and available at
#     http://www.eclipse.org/legal/epl-v10.html
#
#     U.S. Government Users Restricted Rights:  Use, duplication or disclosure
#     restricted by GSA ADP Schedule Contract with IBM Corp.
###########################################################
#  sudo ansible-playbook -i hosts  <this.yml>

- hosts: server
  tasks:
  - name: Skip any activation if bbserver is running
    command:  /bin/systemctl status bbserver.service 
    register: bbserver_service_result
    ignore_errors: yes
    changed_when: false

  - debug:
      msg:  bbserver.service is not running
    when: bbserver_service_result.rc != 0

- hosts: compute
  tasks:
  - name: Skip any activation if bbproxy is running
    command:  /bin/systemctl status bbproxy.service 
    register: bbproxy_service_result
    ignore_errors: yes
    changed_when: false

  - debug:
      msg:  bbproxy.service is not running
    when: bbproxy_service_result.rc != 0

  - name: check export_layout module is loaded
    shell: lsmod |grep export_layout 
    register: export_layout_loaded
    ignore_errors: yes
    changed_when: false

  - debug:
      msg: export_layout module is NOT loaded
    when:  export_layout_loaded.rc != 0 
   
