###########################################################
#     bbInstall.yml
#
#     Copyright IBM Corporation 2020. All Rights Reserved
#
#     This program is licensed under the terms of the Eclipse Public License
#     v1.0 as published by the Eclipse Foundation and available at
#     http://www.eclipse.org/legal/epl-v10.html
#
#     U.S. Government Users Restricted Rights:  Use, duplication or disclosure
#     restricted by GSA ADP Schedule Contract with IBM Corp.
###########################################################
#  sudo ansible-playbook -i hosts  <this.yml>

- hosts: all
  tasks:
  - name: check all nodes for RPM directory
    command: ls -d  {{BBRPMDIR}} 
    any_errors_fatal: true

- hosts: launch
  tasks:
  - name: install BB RPMs on launch node
    shell: "yum localinstall -y {{BBRPMDIR}}/ibm-burstbuffer-[1tml]*rpm {{BBRPMDIR}}/ibm-flightlog-1*.rpm"
    args:
      warn: false # set warn=false to prevent warning       

- hosts: server
  tasks:
  - name: Skip any activation if bbserver is running
    command:  /bin/systemctl status bbserver.service 
    register: bbserver_service_result
    ignore_errors: yes

  - name: Install BB RPMs on ESS
    shell: "yum localinstall -y {{BBRPMDIR}}/ibm-burstbuffer-1*.rpm {{BBRPMDIR}}/ibm-flightlog-1*.rpm"
    args:
      warn: false # set warn=false to prevent warning
    when: bbserver_service_result.rc != 0
    any_errors_fatal: true

  - name: systemctl daemon-reload on ESS
    command: systemctl daemon-reload  

- hosts: compute
  tasks:
  - name: check export_layout module is loaded
    shell: lsmod |grep export_layout 
    register: export_layout_loaded
    ignore_errors: yes

  - name: install export RPM on Compute
    shell: "yum localinstall -y {{BBRPMDIR}}/ibm-export_layout*.rpm"
    args:
      warn: false # set warn=false to prevent warning 
    when: export_layout_loaded.rc != 0
    ignore_errors: yes
   
  - name: Again check export_layout module is loaded
    shell: lsmod |grep export_layout 
    any_errors_fatal: true
    
  - name: Skip any activation if bbproxy is running
    command:  /bin/systemctl status bbproxy.service 
    register: bbproxy_service_result
    ignore_errors: yes

  - name: install BB RPMs on Compute
    shell: "yum localinstall -y {{BBRPMDIR}}/ibm-burstbuffer-[1t]*.rpm {{BBRPMDIR}}/ibm-flightlog-1*.rpm"
    args:
      warn: false # set warn=false to prevent warning 
    when: bbproxy_service_result.rc != 0

  - name: bb systemctl daemon-reload on compute
    command: systemctl daemon-reload
    when: bbproxy_service_result.rc != 0
    


   
