=head1 NAME

bbactivate - setup burst buffer on the node

=head1 SYNOPSIS

/opt/ibm/bb/scripts/bbactivate --cn

/opt/ibm/bb/scripts/bbactivate --ln --bscfswork=/gpfs/gpfs0/bscfswork --envdir= --lsfdir=$LSF_SERVERDIR

/opt/ibm/bb/scripts/bbactivate --server --metadata=/gpfs/gpfs0/bbmetadata 


=head1 DESCRIPTION

For a compute node (--cn), it will setup an NVMe over Fabrics target, configuration files, and start bbProxy.  bbProxy will then attempt to connect to either its primary or backup bbServer.

For a server node (--server), it will setup the configuration files and start bbServer

For a launch node (--ln), it will setup the configuration files for bbcmd.


=over 8

=item B<--nodelist>

Path to a file containing a list of compute nodes in the cluster.  This node list will be used 
with the esslist to statically assign the primary and backup bbServer nodes for the compute node that is executing bbactivate.

The format of the nodelist should be a xCAT hostname per line.

The default path is /etc/ibm/nodelist

=item B<--esslist>

Path to a file containing a list of bbServer IP addresses in the cluster.  This ESS list will be used 
with the nodelist to statically assign the primary and backup bbServer nodes for the compute node that is executing bbactivate.

The format of the esslist should be one or two IP address per line.  Multiple addresses on the line are treated as redundant backups to each other.  

The default path is /etc/ibm/esslist

=item B<--configtempl>

Path to a file containing a customized bb.cfg template.  The default path is /opt/ibm/bb/scripts/bb.cfg


=item B<--nvmetempl>

Path to a file containing a customized NVMe over Fabrics JSON template.  The default path is /opt/ibm/bb/scripts/nvmet.json


=item B<--outputconfig>

Path to the location file to write the burst buffer configuration file.  The default path is /etc/ibm/bb.cfg

=item B<--outputnvmecfg>

Path to the location of the NVMe over Fabrics target JSON configuration file.  

=item B<--[no]offload>

Enable or disable NVMe over Fabrics hardware target offload support.  Target offload is disabled by default.

=item B<--[no]csm>

Enable or disable utilizing CSM infrastructure.  CSM agents must be active on the node in order to use CSM.  

On login/launch node, CSM infrastructure will be used to send bbcmd rather than using passwordless ssh.
On bbProxy, volume group and logical volumes will be tracked in CSM databases.  RAS messages will also be sent to CSM.  
On bbServer, RAS messages will be sent to CSM.

=item B<--[no]cn>

Specifies bbactivate should configure burst buffer on a compute node.

=item B<--[no]server>

Specifies bbactivate should configure burst buffer on a server node.

=item B<--[no]ln>

Specifies bbactivate should configure burst buffer on a login/launch node.

=item B<--envdir>

Specifies the scratch directory to store user temporary files used for communicating between stage-in, running, and stage-out phases of an LSF job.  
The path should be accessible by both the user and root.  If --envdir is NULL, then the user's home directory (as indicated by getpwnam) will be used.  

=item B<--lsfdir>

When specified, bbactivate will update the LSF's etc/ directory with the esub/epsub and bb pre/post exec scripts.  Normally, this would be --lsfdir=$LSF_SERVERDIR

=item B<--bscfswork>

Specifies the scratch directory for BSCFS temporary files for communicating between the job on the compute node with the BSCFS stage-out scripts regarding pending transfers.  

=item B<--metadata>

Specifies the metadata directory used by the bbServer instances.  All bbServer nodes in the cluster must point to the same directory.

=item B<--dryrun>

bbactivate will output the commands that it would run, but it will not modify the system state.  Configuration files that would have been written are instead sent to stdout unless --drypath is specified.

=item B<--drypath>

When used in combination with --dryrun, the file system changes will be written to file(s) in the directory specified by --drypath instead of the actual file locations.  

=item B<--scriptpath>

Specifies an alternative path for the default configuration file locations.

=item B<--help>

Displays the bbactivate man page

=item B<--skip>

Skips one or more steps of the bbactivate sequence, comma-separated.  Steps:  config,lsf,lvm,nvme,start

=back
