#!/bin/bash
###########################################################
#     BSCFS_stop
#
#     Copyright IBM Corporation 2015,2016. All Rights Reserved
#
#     This program is licensed under the terms of the Eclipse Public License
#     v1.0 as published by the Eclipse Foundation and available at
#     http://www.eclipse.org/legal/epl-v10.html
#
#     U.S. Government Users Restricted Rights:  Use, duplication or disclosure
#     restricted by GSA ADP Schedule Contract with IBM Corp.
###########################################################

PRE_INSTALL_LIST="$BSCFS_WORK_PATH/$LSB_JOBID/pre_install_list"

unique_hosts=$(echo "$LSB_HOSTS" | tr ' ' '\n' | sort -u | grep -v $HOSTNAME | tr '\n' ' ')
for HOST in ${unique_hosts}; do
    echo "Stopping BSCFS on $HOST"
    ssh $HOST fusermount -u $BSCFS_MNT_PATH
done
rm -f $PRE_INSTALL_LIST
