require "logstash/devutils/rake"
Gem::Specification.new do |s|
    s.name      = 'grok_dynamic'
    s.version   = '0.0.1'
    s.summary   = 'This filter is designed to enhance the default grok filter plugin.'
    s.files     = Dir['lib/*','spec/*','*.gemspec','Gemfile','LICENSE','*.md']
    s.test_files= s.files.grep(%r{^(test|spec|features)/})
    # TODO 
    # s.licenses= 
    #
    # Metadata flags.
    s.metadata  = { "logstash_plugin" => "true", "logstash_group" => "ouput" }
    s.add_runtime_dependency "logstash-core", ">= 2.0.0", "< 3.0.0"
    s.add_development_dependency 'logstash-devutils'
end
