###########################################################
#     csmInstall.yml
#
#     Copyright IBM Corporation 2020 All Rights Reserved
#
#     This program is licensed under the terms of the Eclipse Public License
#     v1.0 as published by the Eclipse Foundation and available at
#     http://www.eclipse.org/legal/epl-v10.html
#
#     U.S. Government Users Restricted Rights:  Use, duplication or disclosure
#     restricted by GSA ADP Schedule Contract with IBM Corp.
###########################################################
#  sudo ansible-playbook -i hosts  <this.yml>

#check reachability of all hosts
- hosts: all
  tasks:
  any_errors_fatal: true 

- hosts: management
  tasks:
  - name: Skip any csmd-master activation if already running
    command:  /bin/systemctl status csmd-master.service 
    register: csmdmaster_service_result
    ignore_errors: yes

  - name: Skip any ccsmd-aggregator activation if already running
    command:  /bin/systemctl status csmd-aggregator.service 
    register: csmdaggregator_service_result
    ignore_errors: yes

  - name: install csm RPMs on MN
    shell: "dnf install -y ibm-csm-core ibm-csm-api ibm-csm-db ibm-burstbuffer-mn"
    args:
      warn: false # set warn=false to prevent warning 
    when: csmdmaster_service_result.rc != 0  and  csmdaggregator_service_result.rc != 0

  - name: csm MN daemon-reload on launch
    command: systemctl daemon-reload
    when: csmdmaster_service_result.rc != 0  and  csmdaggregator_service_result.rc != 0

  - name: install BB RAS
    shell: yes | /opt/ibm/csm/db/csm_db_ras_type_script.sh -l csmdb /opt/ibm/bb/scripts/bbras.csv
    ignore_errors: yes
  
  - name:  Removes the csm database csmdb from the system 
    shell:  yes | /opt/ibm/csm/db/csm_db_script.sh -d csmdb
    register: csmdutility_service_result
    ignore_errors: yes
    when: csmdmaster_service_result.rc != 0  and  csmdaggregator_service_result.rc != 0
 
  - name: Create a new csm database csmdb with tables and populated data 
    shell: /opt/ibm/csm/db/csm_db_script.sh -n csmdb
    any_errors_fatal: true
    when: csmdmaster_service_result.rc != 0  and  csmdaggregator_service_result.rc != 0
    
- hosts: launch
  tasks:
  - name: Skip any csmd-utility activation if already running
    command:  /bin/systemctl status csmd-utility.service 
    register: csmdutility_service_result
    ignore_errors: yes

  - name: install CSM RPMs on launch
    shell: "dnf install -y ibm-csm-core ibm-csm-api"
    args:
      warn: false # set warn=false to prevent warning 
    when: csmdutility_service_result.rc != 0    

- hosts: compute
  tasks:
  - name: Skip any csmd-compute activation if already running
    command:  /bin/systemctl status csmd-compute.service 
    register: csmdcompute_service_result
    ignore_errors: yes

  - name: install CSM RPMs on compute
    shell: "dnf install -y ibm-csm-core ibm-csm-api ibm-flightlog"
    args:
      warn: false # set warn=false to prevent warning 
    when: csmdcompute_service_result.rc != 0    

  - name: csm systemctl daemon-reload on compute
    command: systemctl daemon-reload
    when: csmdcompute_service_result.rc != 0  
