###########################################################
#     update.yml
#
#     Copyright IBM Corporation 2020 All Rights Reserved
#
#     This program is licensed under the terms of the Eclipse Public License
#     v1.0 as published by the Eclipse Foundation and available at
#     http://www.eclipse.org/legal/epl-v10.html
#
#     U.S. Government Users Restricted Rights:  Use, duplication or disclosure
#     restricted by GSA ADP Schedule Contract with IBM Corp.
###########################################################
#  See the README

#check to see if all hosts are available--fail if not reachable
- hosts: all
  tasks:
  any_errors_fatal: true

- hosts: localhost
  tasks:
    - name: cwd
      command: pwd  
      register: pwd_info

    - debug: 
         msg: "cwd is {{pwd_info.stdout}} playbook_dir is {{playbook_dir}}" 
    - debug:
        msg:  "BBMETADATA={{BBMETADATA}}"
    - debug:
        msg:  "CASTREPO={{CASTREPO}}"

- hosts: all
  tasks:
    - name: Setup CAST yum repository
      copy: 
        content: "{{ CASTREPO }}" 
        dest:    /etc/yum/vars/castrepo
      any_errors_fatal: true

    - name: Clear dnf cache
      command:  dnf clean all

#check for BB RPMDIR early before doing upgrade
- hosts: server
  tasks:
  - name: check server node for BBMETADATA 
    command: ls -d  {{BBMETADATA}} 
    any_errors_fatal: true    

#section for stopping daemons, removing RPMs, cleaning up
- name:  Include stop of LSF
  import_playbook: "{{playbook_dir}}/lsfStop.yml"
- hosts: localhost
  tasks:
    - debug:
         msg: stop CSM and burstbuffer
- name: Include stop of bb 
  import_playbook: "{{playbook_dir}}/../ansible/bbStop.yml"
- name: Include stop of CSM        
  import_playbook: "{{playbook_dir}}/csmStop.yml" 
- name: Include uninstall of CSM       
  import_playbook: "{{playbook_dir}}/csmUninstall.yml"  
- name: Include bb uninstall       
  import_playbook: "{{playbook_dir}}/../ansible/bbUninstall.yml"   

#section for installing RPMs, starting daemons
- hosts: localhost
  tasks:
    - debug:
         msg: install csm and bb
- name: Build/install node list
  import_playbook: "{{playbook_dir}}/../ansible/nodelist.yml"
- name: Build/install esslist
  import_playbook: "{{playbook_dir}}/../ansible/bbserverIPlist.yml"
- name: Include csm install     
  import_playbook: "{{playbook_dir}}/csmInstall.yml"
  when: useCSM
- name: Include bb install      
  import_playbook: "{{playbook_dir}}/../ansible/bbInstall.yml"
- name: certificate setup     
  import_playbook: "{{playbook_dir}}/../ansible/certificates.yml"   
- name: Include csm start     
  import_playbook: "{{playbook_dir}}/csmStart.yml" 
  when: useCSM
- name: Include bb start      
  import_playbook: "{{playbook_dir}}/../ansible/bbStart.yml"  
- name:  Include start lsf
  import_playbook: "{{playbook_dir}}/lsfStart.yml"
   

