foreach (LVL ${TOPLEVELS})
  get_property(tltargets GLOBAL PROPERTY TOPLEVEL_${LVL}_targets)
  list(LENGTH tltargets tltargets_len)
  if((NOT TARGET ${LVL}) AND (${tltargets_len} GREATER 0))
       add_custom_target(${LVL} DEPENDS ${tltargets} COMMENT "Building toplevel ${LVL}")
  endif()
endforeach(LVL)

get_cmake_property(CPACK_COMPONENTS_ALL COMPONENTS)
foreach (LVL ${CPACK_COMPONENTS_ALL})
  get_property(tltargets GLOBAL PROPERTY COMPONENT_${LVL}_targets)
  list(LENGTH tltargets tltargets_len)
  if((NOT TARGET ${LVL}) AND (${tltargets_len} GREATER 0))
       add_custom_target(${LVL} DEPENDS ${tltargets} COMMENT "Building component ${LVL}")
  endif()
endforeach(LVL)
