=head1 NAME

bbProxy - burst buffer proxy process for the compute nodes

=head1 SYNOPSIS

bbProxy [--help] [--whoami=string] [--instance=value] [--config=path]

=head1 DESCRIPTION

The bbProxy is a burst buffer component that runs on each compute node. It connects
all the programs running on the compute node using the bbAPI to bbServer processes
running on the ESS I/O nodes.

=over 8

=item B<--help>

Display the help text

=item B<--whoami>

Identifies the name of the bbProxy configuration.

=item B<--instance>

Unused

=item B<--config>

Path to the JSON configuration file.

=back
